#!/usr/bin/env php
<?php

require __DIR__.'/src.php';

$contents = '';

$f = fopen( 'php://stdin', 'r' );

while( $line = fgets( $f ) ) {
  $contents .= $line;
}

fclose( $f );

Parser::raw($contents)
    ->parse()
    ->sort()
    ->print();
