#!/usr/bin/env php
<?php

require __DIR__.'/src.php';

$file = @$argv[1];

if(! $file) {
    die("Usage: format-bibtex literature.bib [--save|--print|--log|--dump]\n");
}

$option = ltrim(@$argv[2] ?? '--print', '-');

if(! in_array($option, ['dump', 'log', 'print', 'save'])) {
    throw new Exception('invalid option given. try dump, log, print, or save');
}

Parser::read($file)
    ->parse()
    ->sort()
    ->$option($file);

echo "\n";
